_BASE_: ../trn_turbo_video_maskformer2_R50_bs32_8ep_frame.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
  WEIGHTS: "model_final_86143f.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 100 
INPUT:
  MIN_SIZE_TEST: 480
SOLVER:
  IMS_PER_BATCH: 16
INPUT:
  SAMPLING_FRAME_NUM: 2
